### ISSUE TITLE
E2-US-3-Conect to Database

### ISSUE THREAD

**Issue by nadaaldausari** [pdmiller/ParkIt#24]
As a Parkee, I need to be able to access a database so that I can reserve a spot with less effort, time and risk. 
Acceptance Criteria
1)  Verify that parking spot availability has been updated
2)  Verify that notification system is updated upon new parking availability data
3)  Verify that reservation takes less than 30 seconds for Parkee to complete.

**Comment by transfigure** [comment]
Criteria number 3: Changed to "Verify that reservation takes less than 30 seconds for Parkee to complete." to make it measurable.

**Comment by transfigure** [comment]
Going to close this issue - we do not need this user story. It's not functionality, but technical debt.
